// Generated by https://quicktype.io

export interface LoginData {
    correo: string;
    password: string;
}

export interface LoginResponse {
    total:    number;
    usuarios: Usuario[];
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    uid:    string;
    img:    string;
}
